### PR TITLE
WIP create id field with kind stored (Entity, Registry, etc.)

### PR DESCRIPTION
**Pull request by georgolden**
- [x] tests and linter show no problems (`npm t`)
- [x] tests are added/updated for bug fixes and new features
- [x] code is properly formatted (`npm run fmt`)
- [ ] description of changes is added in CHANGELOG.md
- [ ] update .d.ts typings

please do not land before https://github.com/metarhia/metaschema/pull/407

Impelemented https://github.com/metarhia/metaschema/issues/398

### CODE REVIEW

**Review by tshemsedinov — COMMENTED** [review]
It's strange! This PR contains all commits from https://github.com/metarhia/metaschema/pull/407

**Comment by georgolden** [comment]
This is forked from branch in https://github.com/metarhia/metaschema/pull/407

**Comment by tshemsedinov** [comment]
If it is forked from `enchancement/2.0.0-alpha-refactoring` so it's better to merge into this branch, not a master, or marked as WIP with a comment `should be rebased on master after landing #407`.

**Comment by georgolden** [comment]
WIP with a comment should be rebased on master after landing #407

**Pull request closed without merging**
